<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            ['nik' => '02A012', 'nama' => 'Nur Subhaan Febriyanto'],
            ['nik' => '02A016', 'nama' => 'Adi Suryadi'],
            ['nik' => '02A071', 'nama' => 'Matin Hidayat'],
            ['nik' => '02A060', 'nama' => 'Ilham Irpana Rahman'],
            ['nik' => '02A066', 'nama' => 'Kevin Tanoen'],
            ['nik' => '02A082', 'nama' => 'Rendiyansah'],
            ['nik' => '02A1171', 'nama' => 'Ricky Dwi Firmawan'],
            ['nik' => '02A1293', 'nama' => 'Ahmad Fauzi'],
            ['nik' => '02A1294', 'nama' => 'Haikal Setiawan'],
            ['nik' => '02A1295', 'nama' => 'Memey Hermawati'],
            ['nik' => '02A1296', 'nama' => 'Wisnu Aditia'],
            ['nik' => 'E000020', 'nama' => 'Irfan Anugrah Shakti'],
            ['nik' => 'E000029', 'nama' => 'Oka Tobriyana'],
            ['nik' => '02A1327', 'nama' => 'Riski Ramadhani'],
            ['nik' => 'E000025', 'nama' => 'Depi Al Ambari'],
            ['nik' => '02A852', 'nama' => 'Aryanto'],
            ['nik' => 'E000055', 'nama' => 'Imam Antonio'],
            ['nik' => 'E000058', 'nama' => 'Egi Noviar'],
            ['nik' => 'E000042', 'nama' => 'Muhamad Yanuari Priansyah'],
            ['nik' => 'E000075', 'nama' => 'Muhamad Rikza Nugraha'],
            ['nik' => 'E000030', 'nama' => 'Aaliyah Nabilah'],
            ['nik' => 'E000070', 'nama' => 'Rasya Firmansyah'],
            ['nik' => 'E000074', 'nama' => 'Aprian Dwi Setiawan'],
            ['nik' => 'E000094', 'nama' => 'Avicena'],
            ['nik' => 'E000060', 'nama' => 'Kafka Abdi Pradita'],
            ['nik' => 'E000110', 'nama' => 'Ahmad Dadan H'],
            ['nik' => 'E000109', 'nama' => 'Devin Fathir R'],
            ['nik' => 'E000026', 'nama' => 'Alia Atsna Kirana'],
            ['nik' => 'E000027', 'nama' => 'Nadya Putri Argina'],
            ['nik' => 'E000073', 'nama' => 'Kelvin Romadhon'],
            ['nik' => 'E000072', 'nama' => 'Ahmad Husen Al Bukhori'],
            ['nik' => 'E000028', 'nama' => 'Elga Lidya Suhendi'],
            ['nik' => 'E000041', 'nama' => 'Lingga Aprilian'],
            ['nik' => '02A057', 'nama' => 'Haris Emil Wonok'],
            ['nik' => 'E000019', 'nama' => 'Tetdy Lukmana S'],
            ['nik' => '02A1334', 'nama' => 'Gusnur Alfauzi'],
            ['nik' => 'E000071', 'nama' => 'Malvin Tyas Arissaputra'],
            ['nik' => '02A074', 'nama' => 'M Naofal Firdaus'],
            ['nik' => '02A1306', 'nama' => 'Sigit Pamungkas'],
            ['nik' => 'E000059', 'nama' => 'Sheva Tyo Nugroho'],
            ['nik' => 'E000024', 'nama' => 'Muhamad Nanang Subandi'],
            ['nik' => 'E000084', 'nama' => 'Sofyan Tediyana'],
            ['nik' => 'E000083', 'nama' => 'Fajar Ariyanto'],
            ['nik' => 'E000093', 'nama' => 'Resya Maulana Adidtya'],
            ['nik' => 'E000095', 'nama' => 'Yanto Nado'],
            ['nik' => 'E000096', 'nama' => 'Teguh Pirmansyah'],
            ['nik' => 'E000082', 'nama' => 'Desman Sandy Fau'],
            ['nik' => 'E000107', 'nama' => 'Amjad Eka Maulana Basyir'],
            ['nik' => 'E000100', 'nama' => 'Gregorio Benediktus Dua'],
            ['nik' => 'E000123', 'nama' => 'Saiman Alfariji'],
            ['nik' => '02A011', 'nama' => 'Endang Septiyanto'],
            ['nik' => '02A721', 'nama' => 'Arlon Firmansyah'],
            ['nik' => '02A112', 'nama' => 'Arya Maulana Pani'],
            ['nik' => '02A126', 'nama' => 'Hendrawan Syahputra'],
            ['nik' => 'E000068', 'nama' => 'Iyan Prayoga'],
            ['nik' => 'E000129', 'nama' => 'Muhammad Rafi Risqi Hanif'],
            ['nik' => 'E000128', 'nama' => 'Muhamad Suparman'],
            ['nik' => 'E000127', 'nama' => 'Herman'],
            ['nik' => 'E000131', 'nama' => 'Bima Ramadani'],
            ['nik' => 'E000142', 'nama' => 'Supandi'],
            ['nik' => 'E000143', 'nama' => 'Aris Lesmana'],
            ['nik' => 'E000130', 'nama' => 'Vidiaz Derin Syahputra'],
            ['nik' => 'E000144', 'nama' => 'Aldo Bagus'],
            ['nik' => 'E000147', 'nama' => 'Aditia Nugraha'],
            ['nik' => 'E000173', 'nama' => 'Sanjaya'],
            ['nik' => '02A604', 'nama' => 'Mukhamad Makmun'],
            ['nik' => '02A103', 'nama' => 'Aditiya Ali Pratama'],
            ['nik' => 'E000149', 'nama' => 'Vinsensius Riko'],
            ['nik' => 'E000180', 'nama' => 'Agus Soeleiman'],
            ['nik' => 'E000179', 'nama' => 'Aris Prasetya'],
            ['nik' => 'E000181', 'nama' => 'Eko Haryanto'],
            ['nik' => 'E000184', 'nama' => 'Acep Syahroni'],
            ['nik' => 'E000185', 'nama' => 'Alfath Ramadhan Arifin'],
            ['nik' => 'E000158', 'nama' => 'Wendi Irawan'],
            ['nik' => 'E000189', 'nama' => 'Gusti Prasetiyo'],
            ['nik' => 'E000197', 'nama' => 'Ahmad Maulana'],
            ['nik' => 'E000202', 'nama' => 'M Rizqi R'],
            ['nik' => 'E000223', 'nama' => 'Rivel Vinanda Putra'],
            ['nik' => 'E000224', 'nama' => 'Ridwan M Zidan'],
            ['nik' => 'E000225', 'nama' => 'Hari Arief Gusneil'],
            ['nik' => 'E000257', 'nama' => 'Amarudin'],
            ['nik' => 'E000271', 'nama' => 'Marsel Haikutty'],
            ['nik' => 'E000287', 'nama' => 'Muhamad Rizky Apriansyah'],
            ['nik' => 'E000204', 'nama' => 'Sofrianto Nautani'],
            ['nik' => 'E000226', 'nama' => 'M Maulana Rahmat'],
            ['nik' => 'E000209', 'nama' => 'Perdiansyah'],
            ['nik' => 'E000274', 'nama' => 'M Rifat Al Rasyid'],
            ['nik' => 'E000259', 'nama' => 'Muhammad Abyan Al Fatin'],
            ['nik' => 'E000228', 'nama' => 'Inri Immanuel Pangemanan'],
            ['nik' => 'E000234', 'nama' => 'Aditya Yudhatama'],
            ['nik' => 'E000272', 'nama' => 'Gerald Salhuteru'],
            ['nik' => 'E000296', 'nama' => 'Alexander Wawo'],
            ['nik' => 'E000297', 'nama' => 'Oswaldus Bisu'],
            ['nik' => 'E000298', 'nama' => 'Hiras Simorangkir'],
            ['nik' => 'E000302', 'nama' => 'Ronaldo Umbu Sogar'],
            ['nik' => 'E000308', 'nama' => 'Wawan Setiawan'],
            ['nik' => 'E000313', 'nama' => 'Gregorius Reinaldus Laga'],
            ['nik' => 'E000317', 'nama' => 'Alfarodika Cristo'],
            ['nik' => 'E000319', 'nama' => 'David Benediktus Simbolon'],
            ['nik' => 'E000321', 'nama' => 'Muhammad Rehan'],
            ['nik' => 'E000320', 'nama' => 'Aldo Arya Putra'],
            ['nik' => 'E000323', 'nama' => 'Riski Septianhari Wibowo'],
            ['nik' => 'E000324', 'nama' => 'Muhamad Idris Nur Hikmah'],
            ['nik' => 'E000322', 'nama' => 'Muhammad Pajar Rijki'],
            ['nik' => 'E000332', 'nama' => 'Andika Maulana'],
            ['nik' => 'E000334', 'nama' => 'Muhamad Zaenal Abidin'],
            ['nik' => 'E000333', 'nama' => 'Jorgi Satria Adhyaksa'],
            ['nik' => 'E000335', 'nama' => 'Ary Chandra A'],
            ['nik' => 'E000336', 'nama' => 'Aditia Sumiyatna'],
            ['nik' => 'E000279', 'nama' => 'Saddam Maulana Hansa'],
            ['nik' => 'E000260', 'nama' => 'Ihsan Syamil Maulana'],
            ['nik' => 'E000346', 'nama' => 'Halmin'],
            ['nik' => 'E000345', 'nama' => 'Ropik Maulana'],
            ['nik' => 'E000344', 'nama' => 'M Rizky Apriansyah'],
            ['nik' => 'E000352', 'nama' => 'Agung Setia Budi'],
            ['nik' => 'E000353', 'nama' => 'Aceng Oji Setiawan'],
            ['nik' => 'E000196', 'nama' => 'Muhamad Nizham'],
            ['nik' => 'E000386', 'nama' => 'Richardo Manekat'],
            ['nik' => 'E000430', 'nama' => 'Reza Permana Aditya Puta'],
            ['nik' => 'E000420', 'nama' => 'Nasarius Siga Bhoko'],
            ['nik' => 'E000391', 'nama' => 'Helmontianus Cemeaso'],
            ['nik' => 'E000392', 'nama' => 'Ronaldus Betu'],
            ['nik' => 'E000369', 'nama' => 'Wikry Al Farisi'],
            ['nik' => 'E000221', 'nama' => 'Alif Achmad'],
            ['nik' => 'E000424', 'nama' => 'Hangga W Pratama'],
            ['nik' => 'E000248', 'nama' => 'Dydit Adna'],
            ['nik' => 'E000364', 'nama' => 'Ikbal Nasihin'],
            ['nik' => 'E000440', 'nama' => 'Sigit Purwanto'],
            ['nik' => 'E000444', 'nama' => 'M Rayhannudin'],
            ['nik' => 'E000441', 'nama' => 'M Jajang Nurdaman'],
            ['nik' => 'E000449', 'nama' => 'Hilmi'],
            ['nik' => 'E000256', 'nama' => 'Rizki Taufik'],
            ['nik' => 'E000443', 'nama' => 'M Nasir'],
        ];

        foreach ($employees as $employee) {
            Employee::updateOrCreate(
                ['nik' => $employee['nik']],
                ['nama' => $employee['nama']]
            );
        }
    }
}
